services:
  - type: web
    name: youtube-converter
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/convert-java-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
